basex_session:
    host: localhost
    port: 1984
    user: admin
    password: admin
packages: # The XQuery package dependencies to install when the script runs, if they don't already exist
    - name: org.syriaca.zotero2tei
      namespace: http://syriaca.org/zotero2tei
      location: /home/arren/Documents/GitHub/zotero2bibl/zotero2tei.xqm
    - name: http://www.functx.com
      naespace: http://www.functx.com
      location: https://files.basex.org/modules/expath/functx-1.0.xar
    # TODO: maybe add an option to purge and reinstall? because it won't catch new versions from GitHub if it's already installed
commands: # Do not use REPO INSTALL here, instead include in the packages list, above
    - SET SERIALIZER indent=yes,omit-xml-declaration=no
    - SET EXPORTER indent=yes,omit-xml-declaration=no
zotero_config: /home/arren/Documents/GitHub/zotero2bibl/zotero-config-cbss.xml
script: 
  path: src/xquery/main.xq
  description: Converts a JSON CBSS record to a TEI XML CBSS record